### ISSUE TITLE
Unable to parse F10 to F12 keys

### ISSUE THREAD

**Issue by FlenkerDLR** [lavafroth/sweet#1]
Hello,

i try to bind a shortcut on the F10 to F12 key but the parser is unable to parse these keys. The manual (`man 5 swhkd-keys`) says that these keys are also supported.

I have the following config file in `~/.config/swhkd/swhkdrc`:
```
f12
  xterm
```
When I try to parse this file with `./sweet ~/.config/swhkd/swhkdrc` I get the following error message:
```
Error: unable to parse config file

Caused by:
     --> /home/flen_ti/.config/swhkd/swhkdrc:1:3
      |
    1 | f12
      |   ^---
      |
      = expected command
```

Is there a workaround to also use the F10 to F12 keys for keybindings?

Best regards

**Comment by lavafroth** [comment]
Hello there, thank you for reporting this issue. I'll be coordinating with the org repo to land a fix tomorrow.
